export const EXERCISES = {
  Push: [
    "Bench Press","Incline Bench","Decline Bench","Dumbbell Bench Press","Dumbbell Incline Press",
    "Machine Chest Press","Chest Fly","Machine Chest Fly","Pec Deck","Push-ups","Decline Push-ups",
    "Overhead Press","Dumbbell Overhead Press","Machine Shoulder Press","Pike Push-ups",
    "Tricep Pushdown","Rope Tricep Pushdown","V-Bar Tricep Pushdown","Machine Tricep Dips","Bench Dips",
    "Overhead Tricep Extension","Dumbbell Overhead Extension","EZ-Bar Tricep Extension",
    "Lateral Raise","Dumbbell Lateral Raise","Machine Lateral Raise","Cable Lateral Raise",
    "Front Raise","Dumbbell Front Raise","Plate Front Raise","Barbell Front Raise",
    "Upright Row","Barbell Upright Row","Dumbbell Upright Row",
    "Arnold Press","Dumbbell Arnold Press","Reverse Pec Deck","Smith Machine Bench Press",
    "Close Grip Bench Press","Board Press","Machine Shoulder Press","Plate-loaded Chest Press",
  ],
  Pull: [
    "Deadlift","Sumo Deadlift","Trap Bar Deadlift","Rack Pull","Deadlift Variation",
    "Barbell Row","Incline Bench Row","Underhand Row","Seal Row","Machine Row",
    "Chest Supported Row","Dumbbell Row","Single-Arm Dumbbell Row","Pendulum Row","T-Bar Row",
    "Reverse Pec Deck Row","Pull-ups","Weighted Pull-ups","Assisted Pull-ups","Machine Pull-ups",
    "Lat Pulldown","Wide Grip Lat Pulldown","Close Grip Lat Pulldown","Reverse Grip Lat Pulldown",
    "Machine Lat Pulldown","V-Bar Lat Pulldown","Single Arm Lat Pulldown",
    "Cable Row","Close Grip Cable Row","V-Bar Cable Row","Rope Cable Row","Single-Arm Cable Row",
    "Seated Row","Machine Seated Row","Face Pull","Reverse Fly","Dumbbell Reverse Fly",
    "Machine Reverse Fly","Bicep Curl","Barbell Curl","Dumbbell Curl","Hammer Curl",
    "Cable Curl","Machine Bicep Curl","EZ-Bar Curl","Incline Dumbbell Curl","Preacher Curl",
    "Machine Preacher Curl","Concentration Curl","21s Curl","Reverse Curl","Drag Curl",
    "Shrug","Barbell Shrug","Dumbbell Shrug","Machine Shrug","Cable Shrug","Rack Pull Shrug",
  ],
  Legs: [
    "Squat","Back Squat","Front Squat","Goblet Squat","Dumbbell Squat",
    "Bulgarian Split Squat","Split Squat","Sissy Squat","Jump Squat","Pause Squat",
    "Box Squat","Pin Squat","Leg Press","Machine Leg Press","45-Degree Leg Press",
    "V-Squat","Hack Squat","Smith Machine Squat","Belt Squat","Leveraged Squat",
    "Romanian Deadlift","Dumbbell RDL","Single-Leg RDL","Trap Bar RDL","Smith Machine RDL",
    "Leg Curl","Machine Leg Curl","Lying Leg Curl","Seated Leg Curl","Standing Leg Curl",
    "Single-Leg Leg Curl","Dumbbell Leg Curl","Leg Extension","Machine Leg Extension",
    "Single-Leg Leg Extension","Sissy Squat","Smith Machine Leg Extension",
    "Calf Raise","Standing Calf Raise","Seated Calf Raise","Calf Press on Leg Press",
    "Dumbbell Calf Raise","Smith Machine Calf Raise","Plate Loaded Calf Raise",
    "Leg Press Calf Raise","Decline Calf Raise","Single-Leg Calf Raise",
    "Lunge","Walking Lunge","Dumbbell Lunge","Barbell Lunge","Reverse Lunge",
    "Machine Lunge","Step-up","Box Step-up","Dumbbell Step-up","Bulgarian Split Squat",
    "Adductor Machine","Hip Abduction Machine","Glute Bridge","Single-Leg Glute Bridge",
    "Barbell Glute Bridge","Machine Hack Squat","V-Squat Machine","Smith Machine Leg Press",
  ],
  Core: [
    "Plank","Side Plank","High Plank","Plank Hold","Reverse Plank",
    "Ab Wheel","Ab Wheel Rollout","Ab Wheel Kneeling","Ab Wheel Standing","Ab Wheel Decline",
    "Cable Crunch","Machine Ab Crunch","Decline Situp","Weighted Situp","Dumbbell Situp",
    "Cable Wood Chop","Dumbbell Wood Chop","Landmine Wood Chop","Pallof Press","Cable Pallof Press",
    "Russian Twist","Weighted Russian Twist","Dumbbell Russian Twist","Medicine Ball Slam",
    "Hanging Leg Raise","Hanging Knee Raise","Captain's Chair Leg Raise","Machine Leg Raise",
    "Weighted Hanging Leg Raise","Decline Situp","Decline Weighted Situp","Ab Roller",
    "Suitcase Carry","Dumbbell Suitcase Carry","Kettlebell Suitcase Carry","Barbell Suitcase Carry",
    "Dead Bug","Bird Dog","Superman","Swimming Superman","Hollow Hold",
    "V-Up","Weighted V-Up","Rope Crunch","Rope Machine Crunch","Incline Situp",
    "Decline Crunches","Machine Crunches","Ab Rocket Machine","Leg Press Machine Crunches",
    "Barbell Ab Rollout","Stability Ball Crunch","Stability Ball Pass","Ab Ball Jackknife",
  ],
  Cardio: [
    "Treadmill Running","Treadmill Sprint","Treadmill Walk","Incline Treadmill Walk",
    "Elliptical","Stationary Bike","Assault Bike","Rowing Machine","Stair Climber",
    "Jump Rope","High-Intensity Interval Training","HIIT Sprints","Battle Ropes","Box Jumps",
    "Burpees","Mountain Climbers","Jumping Jacks","High Knees","Lateral Shuffles",
    "Swimming","Pool Running","Rowing","Kayaking","Cycling",
    "Walking","Incline Walking","Hill Sprints","Stair Running","Stairs",
  ],
  Mobility: [
    "Foam Roll","Foam Roll Quads","Foam Roll Hamstrings","Foam Roll Glutes","Foam Roll IT Band",
    "Foam Roll Calves","Foam Roll Upper Back","Foam Roll Lats","Dynamic Stretching",
    "Hip Mobility","Shoulder Mobility","Ankle Mobility","Wrist Mobility","Spine Mobility",
    "Cat-Cow Stretch","Downward Dog","Pigeon Pose","Butterfly Stretch","Quad Stretch",
    "Hamstring Stretch","Hip Flexor Stretch","Shoulder Stretch","Chest Stretch","Back Stretch",
    "Spine Twist Stretch","Child's Pose","Cobra Stretch","Lat Stretch","Tricep Stretch",
    "Hang from Bar","Dead Hang","Scapular Pull-up","Band Pull-aparts","Shoulder Dislocate",
  ],
};

export const INDIAN_FOODS = {
  Breakfast: [
    { name:"Poha (dry)", cal:250, unit:"1 plate" },
    { name:"Idli (2 pcs)", cal:140, unit:"2 pcs" },
    { name:"Idli (3 pcs)", cal:210, unit:"3 pcs" },
    { name:"Dosa (plain)", cal:170, unit:"1 pc" },
    { name:"Masala Dosa", cal:220, unit:"1 pc" },
    { name:"Butter Dosa", cal:260, unit:"1 pc" },
    { name:"Uttapam", cal:190, unit:"1 pc" },
    { name:"Upma (wheat)", cal:200, unit:"1 bowl" },
    { name:"Rava Upma", cal:220, unit:"1 bowl" },
    { name:"Paratha (plain)", cal:280, unit:"1 pc" },
    { name:"Paratha (butter)", cal:320, unit:"1 pc" },
    { name:"Aloo Paratha", cal:350, unit:"1 pc" },
    { name:"Gobi Paratha", cal:340, unit:"1 pc" },
    { name:"Paneer Paratha", cal:360, unit:"1 pc" },
    { name:"Bread + 2 Eggs (fried)", cal:320, unit:"1 serving" },
    { name:"Bread + 2 Eggs (boiled)", cal:280, unit:"1 serving" },
    { name:"Boiled Eggs", cal:78, unit:"1 egg" },
    { name:"Fried Eggs", cal:95, unit:"1 egg" },
    { name:"Scrambled Eggs", cal:140, unit:"2 eggs" },
    { name:"Oats", cal:150, unit:"1 bowl" },
    { name:"Oats + Milk", cal:250, unit:"1 bowl" },
    { name:"Cornflakes", cal:180, unit:"1 bowl" },
    { name:"Wheat Flakes", cal:170, unit:"1 bowl" },
    { name:"Semolina (Suji)", cal:210, unit:"1 bowl" },
    { name:"Rava Idli", cal:160, unit:"2 pcs" },
    { name:"Medu Vada", cal:180, unit:"2 pcs" },
    { name:"Chilla (Pancake)", cal:220, unit:"1 pc" },
    { name:"Moong Chilla", cal:200, unit:"1 pc" },
    { name:"Banana", cal:90, unit:"1 pc" },
    { name:"Apple", cal:95, unit:"1 pc" },
    { name:"Orange", cal:62, unit:"1 pc" },
    { name:"Milk (full fat)", cal:150, unit:"1 glass" },
    { name:"Milk (toned)", cal:130, unit:"1 glass" },
    { name:"Milk (skimmed)", cal:80, unit:"1 glass" },
    { name:"Tea with milk", cal:80, unit:"1 cup" },
    { name:"Black coffee", cal:5, unit:"1 cup" },
    { name:"Lassi (plain)", cal:150, unit:"1 glass" },
    { name:"Lassi (sweet)", cal:220, unit:"1 glass" },
    { name:"Buttermilk (Chaas)", cal:60, unit:"1 glass" },
    { name:"Greek Yogurt", cal:130, unit:"1 cup" },
    { name:"Regular Curd", cal:100, unit:"1 bowl" },
    { name:"Almond", cal:170, unit:"30g" },
    { name:"Walnut", cal:185, unit:"30g" },
    { name:"Cashew", cal:155, unit:"30g" },
    { name:"Raisin", cal:100, unit:"30g" },
    { name:"Date", cal:66, unit:"1 pc" },
    { name:"Puri", cal:200, unit:"1 pc" },
    { name:"Bhatura", cal:400, unit:"1 pc" },
    { name:"Kachori", cal:220, unit:"1 pc" },
    { name:"Jalebi", cal:250, unit:"4 pcs" },
    { name:"Imarti", cal:230, unit:"4 pcs" },
  ],
  Lunch: [
    { name:"Dal Chawal (plain)", cal:450, unit:"1 plate" },
    { name:"Dal Chawal (butter)", cal:520, unit:"1 plate" },
    { name:"Rajma Chawal", cal:500, unit:"1 plate" },
    { name:"Chole Chawal", cal:480, unit:"1 plate" },
    { name:"Chole Bhature", cal:650, unit:"1 plate" },
    { name:"Chicken Curry + Rice", cal:550, unit:"1 plate" },
    { name:"Mutton Curry + Rice", cal:600, unit:"1 plate" },
    { name:"Fish Curry + Rice", cal:480, unit:"1 plate" },
    { name:"Prawn Curry + Rice", cal:470, unit:"1 plate" },
    { name:"Paneer Curry + Rice", cal:520, unit:"1 plate" },
    { name:"Butter Chicken + Rice", cal:620, unit:"1 plate" },
    { name:"Tikka Masala + Rice", cal:580, unit:"1 plate" },
    { name:"Vindaloo + Rice", cal:560, unit:"1 plate" },
    { name:"Rogan Josh + Rice", cal:540, unit:"1 plate" },
    { name:"Biryani (veg)", cal:450, unit:"1 plate" },
    { name:"Biryani (chicken)", cal:550, unit:"1 plate" },
    { name:"Biryani (mutton)", cal:620, unit:"1 plate" },
    { name:"Biryani (fish)", cal:500, unit:"1 plate" },
    { name:"Pulao (veg)", cal:380, unit:"1 plate" },
    { name:"Pulao (chicken)", cal:480, unit:"1 plate" },
    { name:"Sambar Rice", cal:380, unit:"1 plate" },
    { name:"Rasam Rice", cal:320, unit:"1 plate" },
    { name:"Roti (wheat)", cal:70, unit:"1 roti" },
    { name:"Roti (whole wheat)", cal:80, unit:"1 roti" },
    { name:"Butter Roti", cal:120, unit:"1 roti" },
    { name:"Naan (plain)", cal:300, unit:"1 pc" },
    { name:"Butter Naan", cal:380, unit:"1 pc" },
    { name:"Tandoori Naan", cal:320, unit:"1 pc" },
    { name:"Roti + Dal", cal:350, unit:"2 roti" },
    { name:"Roti + Sabzi", cal:400, unit:"2 roti" },
    { name:"Paratha + Curry", cal:520, unit:"1 serving" },
    { name:"Chapati + Dal", cal:350, unit:"2 chapati" },
    { name:"Pav Bhaji", cal:500, unit:"1 plate" },
    { name:"Paneer Sabzi", cal:280, unit:"1 bowl" },
    { name:"Mixed Veg Curry", cal:220, unit:"1 bowl" },
    { name:"Aloo Gobi", cal:200, unit:"1 bowl" },
    { name:"Baingan Bharta", cal:180, unit:"1 bowl" },
    { name:"Palak Paneer", cal:300, unit:"1 bowl" },
    { name:"Chana Masala", cal:350, unit:"1 bowl" },
    { name:"Rajma (kidney beans)", cal:280, unit:"1 bowl" },
    { name:"Chole (chickpeas)", cal:320, unit:"1 bowl" },
    { name:"Dal Makhani", cal:400, unit:"1 bowl" },
    { name:"Dal Tadka", cal:350, unit:"1 bowl" },
    { name:"Moong Dal", cal:200, unit:"1 bowl" },
    { name:"Masoor Dal", cal:220, unit:"1 bowl" },
    { name:"Urad Dal", cal:240, unit:"1 bowl" },
    { name:"Sambhar", cal:280, unit:"1 bowl" },
    { name:"Rasam (soup)", cal:100, unit:"1 bowl" },
    { name:"Dahi (curd)", cal:100, unit:"1 bowl" },
    { name:"Raita (yogurt)", cal:150, unit:"1 bowl" },
    { name:"Pickle", cal:30, unit:"1 spoon" },
    { name:"Papad", cal:50, unit:"1 pc" },
    { name:"Khichdi", cal:350, unit:"1 bowl" },
    { name:"Pulao (plain)", cal:400, unit:"1 plate" },
    { name:"Fried Rice", cal:450, unit:"1 plate" },
    { name:"Hakka Noodles", cal:480, unit:"1 plate" },
    { name:"Chow Mein", cal:500, unit:"1 plate" },
  ],
  Dinner: [
    { name:"Khichdi (plain)", cal:350, unit:"1 bowl" },
    { name:"Khichdi (with ghee)", cal:420, unit:"1 bowl" },
    { name:"Sabzi + Roti", cal:400, unit:"2 roti" },
    { name:"Egg Bhurji + Roti", cal:420, unit:"1 plate" },
    { name:"Scrambled Eggs + Roti", cal:380, unit:"1 plate" },
    { name:"Dal Tadka + Rice", cal:430, unit:"1 plate" },
    { name:"Dal + Roti", cal:380, unit:"2 roti" },
    { name:"Palak Paneer + Roti", cal:380, unit:"1 plate" },
    { name:"Moong Dal", cal:200, unit:"1 bowl" },
    { name:"Masoor Dal", cal:220, unit:"1 bowl" },
    { name:"Chicken Curry", cal:280, unit:"1 plate" },
    { name:"Chicken Grilled", cal:250, unit:"100g" },
    { name:"Chicken Tikka", cal:250, unit:"100g" },
    { name:"Grilled Fish", cal:200, unit:"100g" },
    { name:"Tandoori Fish", cal:220, unit:"100g" },
    { name:"Tandoori Roti", cal:120, unit:"2 pcs" },
    { name:"Paneer Tikka", cal:300, unit:"100g" },
    { name:"Prawn Grilled", cal:180, unit:"100g" },
    { name:"Mutton Curry", cal:350, unit:"1 plate" },
    { name:"Lamb Curry", cal:360, unit:"1 plate" },
    { name:"Shrimp Curry", cal:280, unit:"1 plate" },
    { name:"Tofu (grilled)", cal:150, unit:"100g" },
    { name:"Lentil Soup", cal:180, unit:"1 bowl" },
    { name:"Vegetable Soup", cal:120, unit:"1 bowl" },
    { name:"Tomato Soup", cal:140, unit:"1 bowl" },
    { name:"Mulligatawny Soup", cal:200, unit:"1 bowl" },
    { name:"Rice + Curry", cal:480, unit:"1 plate" },
    { name:"Roti + Curry", cal:420, unit:"2 roti" },
    { name:"Naan + Curry", cal:580, unit:"1 serving" },
    { name:"Paratha + Curry", cal:520, unit:"1 serving" },
    { name:"Biryani", cal:500, unit:"1 plate" },
    { name:"Pulao", cal:420, unit:"1 plate" },
    { name:"Fried Rice", cal:450, unit:"1 plate" },
    { name:"Noodles", cal:480, unit:"1 plate" },
    { name:"Sambar Rice", cal:380, unit:"1 plate" },
    { name:"Curd Rice", cal:300, unit:"1 plate" },
    { name:"Lemon Rice", cal:340, unit:"1 plate" },
    { name:"Coconut Rice", cal:380, unit:"1 plate" },
    { name:"Peas Pulao", cal:400, unit:"1 plate" },
    { name:"Mixed Vegetable", cal:220, unit:"1 bowl" },
    { name:"Green Salad", cal:80, unit:"1 bowl" },
    { name:"Cucumber Raita", cal:120, unit:"1 bowl" },
    { name:"Onion Salad", cal:40, unit:"1 bowl" },
    { name:"Tomato Salad", cal:50, unit:"1 bowl" },
  ],
  Snacks: [
    { name:"Chana (roasted)", cal:200, unit:"1 cup" },
    { name:"Peanuts (roasted)", cal:285, unit:"50g" },
    { name:"Peanuts (fried)", cal:315, unit:"50g" },
    { name:"Sprouts (raw)", cal:120, unit:"1 bowl" },
    { name:"Sprouts Salad", cal:150, unit:"1 bowl" },
    { name:"Samosa", cal:260, unit:"1 pc" },
    { name:"Samosa (fried)", cal:300, unit:"1 pc" },
    { name:"Bhel Puri", cal:180, unit:"1 plate" },
    { name:"Pani Puri", cal:150, unit:"6 pcs" },
    { name:"Gol Gappa", cal:120, unit:"6 pcs" },
    { name:"Momos (veg)", cal:220, unit:"6 pcs" },
    { name:"Momos (chicken)", cal:280, unit:"6 pcs" },
    { name:"Spring Roll", cal:200, unit:"2 pcs" },
    { name:"Pakora (veg)", cal:240, unit:"100g" },
    { name:"Onion Pakora", cal:220, unit:"100g" },
    { name:"Aloo Tikki", cal:180, unit:"1 pc" },
    { name:"Vada (medu)", cal:180, unit:"2 pcs" },
    { name:"Chikali (corn)", cal:160, unit:"1 pc" },
    { name:"Protein Bar", cal:220, unit:"1 bar" },
    { name:"Protein Bar (nuts)", cal:250, unit:"1 bar" },
    { name:"Granola Bar", cal:200, unit:"1 bar" },
    { name:"Energy Bar", cal:180, unit:"1 bar" },
    { name:"Greek Yogurt", cal:130, unit:"1 cup" },
    { name:"Greek Yogurt (honey)", cal:180, unit:"1 cup" },
    { name:"Regular Curd", cal:100, unit:"1 bowl" },
    { name:"Whey Protein", cal:120, unit:"1 scoop" },
    { name:"Almonds", cal:170, unit:"30g" },
    { name:"Walnuts", cal:185, unit:"30g" },
    { name:"Cashews", cal:155, unit:"30g" },
    { name:"Sunflower Seeds", cal:175, unit:"30g" },
    { name:"Pumpkin Seeds", cal:165, unit:"30g" },
    { name:"Raisins", cal:100, unit:"30g" },
    { name:"Dates", cal:66, unit:"1 pc" },
    { name:"Dates (2 pcs)", cal:132, unit:"2 pcs" },
    { name:"Dried Apricot", cal:67, unit:"30g" },
    { name:"Dried Mango", cal:150, unit:"30g" },
    { name:"Apple", cal:95, unit:"1 pc" },
    { name:"Banana", cal:90, unit:"1 pc" },
    { name:"Orange", cal:62, unit:"1 pc" },
    { name:"Guava", cal:112, unit:"1 pc" },
    { name:"Papaya", cal:88, unit:"200g" },
    { name:"Mango", cal:135, unit:"1 pc" },
    { name:"Grapes", cal:87, unit:"1 cup" },
    { name:"Watermelon", cal:46, unit:"1 cup" },
    { name:"Buttermilk (Chaas)", cal:60, unit:"1 glass" },
    { name:"Makhana (roasted)", cal:100, unit:"1 cup" },
    { name:"Chikhalwali (corn)", cal:120, unit:"1 cup" },
    { name:"Roasted Gram", cal:200, unit:"1 cup" },
    { name:"Puffed Rice", cal:100, unit:"1 cup" },
    { name:"Murukku", cal:180, unit:"100g" },
    { name:"Chivda (mix)", cal:220, unit:"100g" },
    { name:"Namkeen (saltine)", cal:160, unit:"50g" },
    { name:"Chips (potato)", cal:200, unit:"30g" },
    { name:"Chips (corn)", cal:190, unit:"30g" },
    { name:"Cookies (plain)", cal:150, unit:"2 pcs" },
    { name:"Rusks", cal:120, unit:"2 pcs" },
    { name:"Biscuits (plain)", cal:80, unit:"2 pcs" },
    { name:"Cake (sponge)", cal:250, unit:"1 slice" },
    { name:"Kheer (rice pudding)", cal:300, unit:"1 bowl" },
    { name:"Halwa", cal:350, unit:"1 bowl" },
    { name:"Gulab Jamun", cal:200, unit:"2 pcs" },
    { name:"Jalebi", cal:250, unit:"4 pcs" },
    { name:"Imarti", cal:230, unit:"4 pcs" },
    { name:"Laddu", cal:180, unit:"1 pc" },
    { name:"Barfi", cal:200, unit:"1 pc" },
    { name:"Peda", cal:120, unit:"2 pcs" },
    { name:"Besan Laddu", cal:200, unit:"1 pc" },
    { name:"Coconut Laddu", cal:180, unit:"1 pc" },
    { name:"Kaju Katli", cal:220, unit:"1 piece" },
    { name:"Chocolate", cal:160, unit:"30g" },
    { name:"Dark Chocolate", cal:155, unit:"30g" },
    { name:"Ice Cream", cal:200, unit:"1 scoop" },
    { name:"Kulfi", cal:180, unit:"1 pc" },
    { name:"Falooda", cal:280, unit:"1 glass" },
    { name:"Lassi (plain)", cal:150, unit:"1 glass" },
    { name:"Lassi (sweet)", cal:220, unit:"1 glass" },
    { name:"Lassi (mango)", cal:240, unit:"1 glass" },
    { name:"Juice (fresh)", cal:120, unit:"1 glass" },
    { name:"Juice (packaged)", cal:140, unit:"1 glass" },
    { name:"Smoothie", cal:280, unit:"1 glass" },
    { name:"Milkshake", cal:320, unit:"1 glass" },
    { name:"Coconut Water", cal:45, unit:"1 glass" },
    { name:"Sugarcane Juice", cal:180, unit:"1 glass" },
  ],
};

export const EXERCISE_VIDEOS = {
  Push: [
    { name:"Bench Press",       id:"rT7DgCr-3pg", tips:"Keep shoulder blades pinched, feet flat, bar over lower chest." },
    { name:"Incline Bench",     id:"DbFgADa2PL8", tips:"Set bench 30–45°. Control the descent, press toward chin." },
    { name:"Overhead Press",    id:"2yjwXTZQDDI", tips:"Brace core, tuck elbows slightly, squeeze glutes at top." },
    { name:"Tricep Pushdown",   id:"2-LAMcpzODU", tips:"Keep elbows pinned to sides, full extension at bottom." },
    { name:"Chest Fly",         id:"eozdVDA78K0", tips:"Slight bend in elbows throughout, feel the stretch at bottom." },
    { name:"Dips",              id:"2z8JmcrW-As", tips:"Lean forward for chest, upright for triceps. Full ROM." },
    { name:"Lateral Raise",     id:"3VcKaXpzqRo", tips:"Lead with elbows, slight bend, stop at shoulder height." },
  ],
  Pull: [
    { name:"Deadlift",          id:"op9kVnSso6Q", tips:"Bar over mid-foot, neutral spine, drive floor away." },
    { name:"Pull-ups",          id:"eGo4IYlbE5g", tips:"Dead hang start, drive elbows to hips, chin over bar." },
    { name:"Lat Pulldown",      id:"CAwf7n6Luuc", tips:"Lean back slightly, pull to upper chest, control the rise." },
    { name:"Cable Row",         id:"GZbfZ033f74", tips:"Sit tall, pull to navel, squeeze shoulder blades together." },
    { name:"Face Pull",         id:"rep-qVOkqgk", tips:"Pull to forehead level, external rotation at end." },
    { name:"Bicep Curl",        id:"ykJmrZ5v0Oo", tips:"Keep elbows fixed, full extension, slow on the way down." },
  ],
  Legs: [
    { name:"Squat",             id:"ultWZbUMPL8", tips:"Chest up, knees track toes, break parallel if mobile." },
    { name:"Romanian Deadlift", id:"JCXUYuzwNrM", tips:"Soft knee bend, push hips back, bar stays close to legs." },
    { name:"Leg Curl",          id:"ELOCsoDSmrg", tips:"Control the return, full contraction at top." },
    { name:"Leg Extension",     id:"YyvSfVjQeL0", tips:"Pause at top, lower slowly, don't swing." },
    { name:"Hack Squat",        id:"0tn5K9NlCfo", tips:"Feet high on plate for glutes, low for quads." },
  ],
  Core: [
    { name:"Plank",             id:"ASdvN_XEl_c", tips:"Neutral spine, squeeze glutes & abs, breathe steadily." },
    { name:"Russian Twist",     id:"JyUqwkVpsi8", tips:"Lean back 45°, rotate fully each side, feet off floor." },
  ],
};

export const C = {
  primary:  "#3B82F6",
  bg:       "#F0F5FF",
  card:     "#FFFFFF",
  border:   "#DBEAFE",
  muted:    "#93A8C8",
  success:  "#22C55E",
  warning:  "#F59E0B",
  surface:  "#EEF4FF",
  dark:     "#1E3A5F",
  red:      "#EF4444",
};

export const MEAL_EMOJI = { Breakfast:"🌅", Lunch:"☀️", Dinner:"🌙", Snacks:"🍎" };